# Generated by Django 2.0.6 on 2018-07-04 11:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofileinfo_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('java', 'Java'), ('django', 'Django'), ('html', 'HTML'), ('css', 'CSS'), ('javascript', 'Javascript'), ('angular', 'Angular')], max_length=46)),
            ],
        ),
    ]
