# Generated by Django 2.0.5 on 2018-07-04 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_skills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
