# Generated by Django 2.0.5 on 2018-07-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofileinfo_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(default='https://www.watsonmartin.com/wp-content/uploads/2016/03/default-profile-picture.jpg', upload_to='profile_pics'),
        ),
    ]
