# Generated by Django 2.0.5 on 2018-07-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='New Group', max_length=200),
        ),
    ]
