# Generated by Django 2.0.5 on 2018-07-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20180706_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', through='groups.GroupMember', to='accounts.UserProfileInfo'),
        ),
    ]
