# Generated by Django 2.0.5 on 2018-07-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180705_2135'),
        ('groups', '0003_auto_20180706_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now=True)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='groups.GroupMember', to='accounts.UserProfileInfo'),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to='accounts.UserProfileInfo'),
        ),
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='request',
            name='sent_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='accounts.UserProfileInfo'),
        ),
    ]
